CREATE DATABASE DEPARTMENTS;
USE DEPARTMENTS;
CREATE TABLE DEPT(DEPTNO INT,DNAME VARCHAR(15),LOCATION VARCHAR(15),PRIMARY KEY(DEPTNO));
RENAME TABLE DEPT TO DEPARTMENT;
ALTER TABLE DEPARTMENT ADD PINCODE INT NOT NULL ;
ALTER TABLE DEPARTMENT DROP COLUMN PINCODE;
ALTER TABLE DEPARTMENT RENAME COLUMN DNAME TO DEPT_NAME;
ALTER TABLE  DEPARTMENT  MODIFY LOCATION CHAR(10);
DROP TABLE DEPARTMENT;